---
- hosts: master[0]
  become: true
  become_method: sudo
  tasks:
    - name: Generate the join command
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_command_output
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Set the join command as a fact
      ansible.builtin.set_fact:
        join_command: "{{ join_command_output.stdout.split() | join(' ') }}"

- hosts: join[0]
  become: true
  become_method: sudo
  tasks:
    - name: Check if node is already joined
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kube_joined_status

    - name: Set the CRI Socket Path
      ansible.builtin.set_fact:
        cri_socket: "{{ {
          'Docker': 'unix:///var/run/cri-dockerd.sock',
          'Containerd': 'unix:///run/containerd/containerd.sock',
          'CRI-O': 'unix:///var/run/crio/crio.sock'
        }[cri] }}"

    - name: Verify etcd health before joining a new control-plane
      shell: "KUBECONFIG=/etc/kubernetes/admin.conf kubectl get --raw='/readyz?verbose' | grep etcd"
      register: etcd_health_prejoin
      retries: 20
      delay: 15
      until: etcd_health_prejoin.rc == 0
      delegate_to: "{{ groups['master'][0] }}"
      become_user: root
      when:
        - not kube_joined_status.stat.exists

    - name: Join the Worker Node
      ansible.builtin.shell: "{{ hostvars[groups['master'][0]]['join_command'] }} --cri-socket {{ cri_socket }}"
      when:
        - ansible_distribution_file_variety == "Debian"
        - not kube_joined_status.stat.exists

    - name: Wait until etcd cluster is healthy
      shell: "KUBECONFIG=/etc/kubernetes/admin.conf kubectl get --raw='/readyz?verbose' | grep etcd"
      register: etcd_health_postjoin
      retries: 20
      delay: 15
      until: etcd_health_postjoin.rc == 0
      delegate_to: "{{ groups['master'][0] }}"
      become_user: root
...