---
- hosts: masters
  become: true
  become_method: sudo
  tasks:
    - name: Generate the join command
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_command_output

    - name: Print the join command
      ansible.builtin.debug:
        msg: "{{ join_command_output.stdout }}"
...