---
- hosts: all_vms
  become: true
  become_method: sudo
  tasks:
    - name: Wait for dpkg lock release
      shell: |
        while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          sleep 5
        done
      retries: 30
      delay: 10
      register: wait_dpkg
      until: wait_dpkg.rc == 0

    - name: Store the initialization file on each VM
      ansible.builtin.copy:
        src: ../init.sh
        dest: /tmp/init.sh
        mode: '0755'
      when: ansible_distribution_file_variety == "Debian"
    
    - name: Initialize each VM to become a K8S Node [~ 2 minutes]
      ansible.builtin.command: /tmp/init.sh {{ ansible_host }} {{ cri }}
      when: ansible_distribution_file_variety == "Debian"
...